name: eeg2text
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
dependencies:
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pytorch-cuda=11.6
  - scipy=1.11.1
  - h5py=3.7.0
  - tqdm=4.65.0
  - transformers=4.28.1
  - wandb=0.15.10
